import { createElementView } from "@/lib/create-element-view";
import {
    alanine,
    arginine,
    asparagine,
    asparticAcid,
    cysteine,
    glutamicAcid,
    glutamine,
    glycine,
    histidine,
    isoleucine,
    leucine,
    lysine,
    methionine,
    phenylalanine,
    proline,
    serine,
    threonine,
    tryptophan,
    tyrosine,
    valine,
} from "@/data/protein-elements";

export const AminoMap = {
    Leucine: createElementView(leucine),
    Isoleucine: createElementView(isoleucine),
    Valine: createElementView(valine),
    Lysine: createElementView(lysine),
    Methionine: createElementView(methionine),
    Phenylalanine: createElementView(phenylalanine),
    Threonine: createElementView(threonine),
    Tryptophan: createElementView(tryptophan),
    Histidine: createElementView(histidine),
    Alanine: createElementView(alanine),
    Arginine: createElementView(arginine),
    Asparagine: createElementView(asparagine),
    AsparticAcid: createElementView(asparticAcid),
    Cysteine: createElementView(cysteine),
    GlutamicAcid: createElementView(glutamicAcid),
    Glutamine: createElementView(glutamine),
    Glycine: createElementView(glycine),
    Proline: createElementView(proline),
    Serine: createElementView(serine),
    Tyrosine: createElementView(tyrosine),
} as const;
